### PR TITLE
Dockered build

### LINKED ISSUE #18: Docker scripts to build portable image
I have created [this project](https://github.com/LiMium/ungoogled-chromium-portable-docker) that contains docker scripts to build a portable image of ungoogled-chromium. It basically just gathers all the dependencies and sets up clang, etc, then calls the scripts from this repo to start the build.

This will simplify the build a lot because:
* the only pre-requisite is `docker`
* works the same on any linux host
* the dependencies don't pollute the host system

Will be more than happy to move the repo to this organisation, if there is interest.

### PR DESCRIPTION
**Pull request by hrj**
closes #18 

~~I haven't managed to complete the build. It is running out of memory in the final LINK stage. Will try it on a beefier machine.~~

~~In the meanwhile, making this pull request in case anyone else wants to try it.~~

Instructions:
* Ensure docker is installed and configured, etc
* Run `./docker-build.sh`

### CODE REVIEW

**Comment by hrj** [comment]
I confirmed that the build works on a larger machine.

**Comment by Eloston** [comment]
Actually wait, I have a few questions (some of which I should have brought up in #18):

1. Would users always call `docker-build.sh` even if they `git pull` a new version of this repo?
2. Can we combine `build-and-pack.sh` into Dockerfile?
3. Would combining the Dockerfile prevent images from being cached? I thought that changing part of the Dockerfile would only affect images from that instruction onward.

**Comment by hrj** [comment]
> * Would users always call `docker-build.sh` even if they `git pull` a new version of this repo?

Yes, they can use normal git operations on this repo, including pull or checkout. The `docker-build.sh` does a submodule update, and then runs the build that matches the current working directory. Any uncommitted changes will also affect the build.

Were you concerned about any particular use-case?

> 
> * Can we combine `build-and-pack.sh` into Dockerfile?

Yeah, I will work on that. Requires some learning for me, but I agree it will be cleaner and worth the trouble.

> 
> * Would combining the Dockerfile prevent images from being cached? I thought that changing part of the Dockerfile would only affect images from that instruction onward.

You are right; the reason for two separate stages is so that we can publish the first stage, not just cache it locally.

But do let me know if you have alternate ideas.

**Comment by hrj** [comment]
> Can we combine build-and-pack.sh into Dockerfile?

Done.

**Comment by Eloston** [comment]
> You are right; the reason for two separate stages is so that we can publish the first stage, not just cache it locally.

I see, how does this publishing work? How do people download and use a published version?

**Comment by hrj** [comment]
> I see, how does this publishing work? How do people download and use a published version?

There is something called as a docker registry. Anyone can host a public or private registry. A "blessed" registry exists at https://hub.docker.com which most people use.

We can publish images to a registry using `docker push` command. And images get pulled either with an explicit `docker pull` command or via referencing an image in a Dockerfile.

In our case, we could publish the first stage docker image. And those who want to get a pre-built image can `docker pull` it, and perhaps save some time (depending on the speed of their network).

I haven't actually tried it with this docker image; I just wanted to keep the option open. If there is strong interest in this, we can spend some more time on it.

**Pull request merged**
